CREATE TABLE Vendeg_hazi
(
  USERNEV VARCHAR(20),
  NEV VARCHAR(50) MASKED WITH (FUNCTION = 'default()'),
  EMAIL VARCHAR(60) MASKED WITH (FUNCTION = 'email()'),
  SZAML_CIM VARCHAR(100) MASKED WITH (FUNCTION = 'partial(5,"XXXXXXX",0)'),
  SZUL_DAT [date] NULL
);